title: Greenid
default_lang: nl
author:
  name: 'Ides De Vlamynck'
  email: stijn@stans.be
taxonomies:
  - category
  - tag
metadata:
  generator: 'Built by stans.be'
  description: 'GreenID, gecertifieerde specialist in boomverzorging sinds 2001 onder leiding van Ides De Vlamynck'
  keywords: 'boomverzorging, westvlaanderen, west, vlaanderen, green, id, ides, certified, treeworker, snoeien, vellen, hakselen, zaaien, klieven, uitfrezen, verzorging, aanplanten, advies, standplaats'
  author: 'Ides De Vlamynck'
  publisher: 'Stijn Anseel'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
routes:
  /uitfrezen: '/activiteiten/uitfrezen'
  /snoeien: '/activiteiten/snoeien'
  /vellen: '/activiteiten/vellen'
  /hakselen: '/activiteiten/hakselen'
  /klieven: '/activiteiten/klieven'
  /verzorging: '/activiteiten/verzorging'
  /aanplanten: '/activiteiten/aanplanten'
  /advies: '/activiteiten/advies'
  /standplaats: '/activiteiten/standplaats'
